//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int ID { get; set; }
        public string message1 { get; set; }
        public string sender_username { get; set; }
        public string receiver_username { get; set; }
    }
}
