//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVEMENT()
        {
            this.PENALTY = new HashSet<PENALTY>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public Nullable<System.DateTime> GET_TIME { get; set; }
        public Nullable<System.DateTime> GIVE_TIME { get; set; }
        public Nullable<System.DateTime> MEMBER_GIVETIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> isPenaltyApplied { get; set; }
    
        public virtual BOOK BOOK1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual MEMBER MEMBER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENALTY> PENALTY { get; set; }
    }
}
