//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENALTY
    {
        public int ID { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<int> MOVEMENT { get; set; }
    
        public virtual MEMBER MEMBER1 { get; set; }
        public virtual MOVEMENT MOVEMENT1 { get; set; }
    }
}
